// <auto-generated />
// This file was generated by CascadeEsdm.EventExtractor. Do not delete it.
// It provides a polyfill for System.Runtime.CompilerServices.IsExternalInit,
// which is required by the C# compiler to support record primary constructors
// and init-only setters when targeting netstandard2.1.

namespace System.Runtime.CompilerServices;

internal static class IsExternalInit { }